In [144]:
import pandas as pd
import numpy as np

# Cleaning
from datetime import datetime, timedelta
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Similiraty 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Save models
import pickle 


import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Please download it once
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

In [40]:
data_user = pd.read_csv('data\survey_results_public.csv')
data_user.head()

,Respondent,Hobby,OpenSource,Country,Student,Employment,FormalEducation,UndergradMajor,CompanySize,DevType,...,Exercise,Gender,SexualOrientation,EducationParents,RaceEthnicity,Age,Dependents,MilitaryUS,SurveyTooLong,SurveyEasy
0,1,Yes,No,Kenya,No,Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,20 to 99 employees,Full-stack developer,...,3 - 4 times per week,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Black or of African descent,25 - 34 years old,Yes,NaN,The survey was an appropriate length,Very easy
1,3,Yes,Yes,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...","10,000 or more employees",Database administrator;DevOps specialist;Full-...,...,Daily or almost every day,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",White or of European descent,35 - 44 years old,Yes,NaN,The survey was an appropriate length,Somewhat easy
2,4,Yes,Yes,United States,No,Employed full-time,Associate degree,"Computer science, computer engineering, or sof...",20 to 99 employees,Engineering manager;Full-stack developer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,No,No,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",100 to 499 employees,Full-stack developer,...,I don't typically exercise,Male,Straight or heterosexual,Some college/university study without earning ...,White or of European descent,35 - 44 years old,No,No,The survey was an appropriate length,Somewhat easy
4,7,Yes,No,South Africa,"Yes, part-time",Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","10,000 or more employees",Data or business analyst;Desktop or enterprise...,...,3 - 4 times per week,Male,Straight or heterosexual,Some college/university study without earning ...,White or of European descent,18 - 24 years old,Yes,NaN,The survey was an appropriate length,Somewhat easy

In [41]:
data_job = pd.read_csv('data\dice_com-job_us_sample.csv')
data_job.head()

,advertiserurl,company,employmenttype_jobstatus,jobdescription,jobid,joblocation_address,jobtitle,postdate,shift,site_name,skills,uniq_id
0,https://www.dice.com/jobs/detail/AUTOMATION-TE...,"Digital Intelligence Systems, LLC","C2H Corp-To-Corp, C2H Independent, C2H W2, 3 M...",Looking for Selenium engineers...must have sol...,Dice Id : 10110693,"Atlanta, GA",AUTOMATION TEST ENGINEER,1 hour ago,Telecommuting not available|Travel not required,NaN,SEE BELOW,418ff92580b270ef4e7c14f0ddfc36b4
1,https://www.dice.com/jobs/detail/Information-S...,University of Chicago/IT Services,Full Time,The University of Chicago has a rapidly growin...,Dice Id : 10114469,"Chicago, IL",Information Security Engineer,1 week ago,Telecommuting not available|Travel not required,NaN,"linux/unix, network monitoring, incident respo...",8aec88cba08d53da65ab99cf20f6f9d9
2,https://www.dice.com/jobs/detail/Business-Solu...,"Galaxy Systems, Inc.",Full Time,"GalaxE.SolutionsEvery day, our solutions affec...",Dice Id : CXGALXYS,"Schaumburg, IL",Business Solutions Architect,2 weeks ago,Telecommuting not available|Travel not required,NaN,"Enterprise Solutions Architecture, business in...",46baa1f69ac07779274bcd90b85d9a72
3,https://www.dice.com/jobs/detail/Java-Develope...,TransTech LLC,Full Time,Java DeveloperFull-time/direct-hireBolingbrook...,Dice Id : 10113627,"Bolingbrook, IL","Java Developer (mid level)- FT- GREAT culture,...",2 weeks ago,Telecommuting not available|Travel not required,NaN,Please see job description,3941b2f206ae0f900c4fba4ac0b18719
4,https://www.dice.com/jobs/detail/DevOps-Engine...,Matrix Resources,Full Time,Midtown based high tech firm has an immediate ...,Dice Id : matrixga,"Atlanta, GA",DevOps Engineer,48 minutes ago,Telecommuting not available|Travel not required,NaN,"Configuration Management, Developer, Linux, Ma...",45efa1f6bc65acc32bbbb953a1ed13b7

# **Recommendation by search**

When conducting a job search, it is crucial to provide job recommendations that precisely match the user's specific criteria. For this purpose, the recommendation function takes into consideration various aspects:

- **Same Title**: Similarity is assessed using vectorization and frequency analysis of the job title.

- **Same Description**: Comparison is performed using vectorization and frequency analysis of the job description.

- *(**Same Skills**: Relevance of required skills is evaluated through vectorization and frequency analysis of mentioned skills.)*

- **Same Company**: A bonus is awarded to jobs from the same company as the initial search.

- **Same Employment Status**: An additional bonus is granted to jobs sharing the same employment status as specified in the search.

- **Same Location**: A filtering function may be applied to return only jobs located in the same geographical region as the search.

- **Recently Posted**: The function can also filter results based on the recency of job postings, providing suggestions that align with freshness criteria.

This multi-criteria approach ensures that recommendations align comprehensively with the user's preferences, considering various factors such as semantic similarity, company affiliation, employment status, location, and posting recency.

In [42]:
data_job = data_job[['company', 'employmenttype_jobstatus', 'jobdescription', 
                     'joblocation_address', 'jobtitle', 'postdate', 'shift', 'skills']]

data_job['jobdescription'][0]

'Looking for Selenium engineers...must have solid java coding skills\xa0I have several openings some 3 month to hire some 6...must be able to go PERM\xa0\xa0This can be someone with 0-5 years of experience. Most important qualities are Eagerness and Aptitude. POSITION PURPOSE - Do you want to be on the forefront of cutting edge technology, introduce solutions to problems that didn’t exist before, and have the ability to see the result of your successes? Our client assures growth by collaborating with development teams and creating tools that aid engineers in building, testing, debugging, and releasing software. We touch millions of users by increasing the rate of development and ensuring our products are methodically tested. We are experts in software health, testability, and sustainability. As a Software Engineer in Test at our client, you can expect to build flexible and scalable solutions while working on some of the most complex challenges in large-scale computing by utilizing your skills in data structures and object oriented programming. MAJOR TASKS, RESPONSIBILITIES AND KEY ACCOUNTABILITIES - Lead and contribute to engineering efforts from planning to execution and delivery to solve complex engineering problems in tools and testing. • Design and build advanced automated testing frameworks. • Build tooling to help Developers measure and increase their velocity. • Adopt best practices in software health, testing, and sustainability. • Analyze and break down complex software systems and collaborate with Development teams to improve the overall design. NATURE AND SCOPE - • Typically reports to Manager Test Engineering • No associates report to the person in this role on a permanent basis • Analyze and resolve complex quality issues critical to solution delivery • Fast-paced environment of freedom and responsibility PREFERRED QUALIFICATIONS • Hands on Java Development experience • Proficient in Ab Initio ETL and Batch testing • Hands-on knowledge of Soap UI, ITKO Lisa, and Selenium • Hands on experience with Unix, KSH, and Bourne Shell Scripting • Strong scripting knowledge with Java, Groovy and Jmeter • Strong development experience working on web services (REST and SOAP) • Experience building test automation frameworks for web services using Soap UI, Groovy, or Lisa • Proficient in SQL • Working knowledge of SVN and Jenkins – build and development process • eCommerce/Retail QA experience • Excellent written and verbal communication skills • Self-motivated with a strong work ethic and a positive attitude • Desire to work in a fast-paced, results orientated team • Experience with a scripting language such as Perl • Passion to understand, learn, dissect and improve new technologies • Proficient in one or more of the following: Retail applications, Windows platform, UNIX platforms, JAVA, Relational Databases, Websphere Application Server, Websphere Commerce, Websphere MQ • Comprehensive understanding of systems, applications and networks KNOWLEDGE, SKILLS, ABILITIES AND COMPETENCIES - • Proficient in one or more of the following: Retail applications, Windows platform, UNIX platforms, MVS COBOL, JAVA, J2EE, Relational Databases, Websphere Application Server, Websphere Commerce, Websphere MQ, Networking (Voice, LAN, WAN), SAP, Siebel, Peoplesoft • Comprehensive understanding of systems, applications and networks • Strong problem solving and analytical skills • Strong oral and written communication skills • Ability to coordinate and collaborate across cross-functional teams\xa0'

In [43]:
# Initialize the WordNet Lemmatizer
lemmatizer = WordNetLemmatizer()

def txt_cleaning(text):
    """
    Clean a given text, typically used for job descriptions and titles.

    Parameters:
    - text (str): The input text to be cleaned.

    Returns:
    str: The cleaned and processed text.

    Steps:
    1. Keep only alpha-numeric characters.
    2. Tokenize the text for better processing.
    3. Apply lemmatization to reduce words to their base form.
    4. Remove common English stop words.
    """
    # Keep only alpha-numeric characters
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

    # Tokenize for better processing
    tokens = word_tokenize(text.lower())

    # Apply lemmatization and remove stop words using list comprehension
    lemmatization = [lemmatizer.lemmatize(w) for w in tokens if w not in stopwords.words('english')]

    return " ".join(lemmatization)

In [44]:
# Example usage
txt = 'Hello world I\'m Axel I am looking for an internship in data science. I have skills in programming, especially Python. \t\n'
cleaned_text = txt_cleaning(txt)
print(cleaned_text)

hello world axel looking internship data science skill programming especially python

In [45]:
# 20 min to run !!!
print('Cleaning jobtitle')
data_job['jobtitle'] = data_job['jobtitle'].apply(lambda x: txt_cleaning(x))

print('Cleaning jobdescription')
data_job['jobdescription'] = data_job['jobdescription'].apply(lambda x: txt_cleaning(x))

def convert_date(date):
    # Remove ' ago' from the date
    date = date.replace(' ago', '')

    # If date is like 'moments ago'
    if len(date.split()) == 1:
        return datetime.now()

    # If date is like '7 minutes ago'
    if date.split(' ')[1] in ['minute', 'minutes']:
        minutes_ago = int(date.split(' ')[0])
        return datetime.now() - timedelta(minutes=minutes_ago)

    # If date is like '2 hours ago'
    if date.split(' ')[1] in ['hour', 'hours']:
        hours_ago = int(date.split(' ')[0])
        return datetime.now() - timedelta(hours=hours_ago)

    # If date is like '2 weeks ago'
    if date.split(' ')[1] in ['week', 'weeks']:
        weeks_ago = int(date.split(' ')[0])
        return datetime.now() - timedelta(weeks=weeks_ago)

    # If date is like '1 month ago'
    if date.split(' ')[1] in ['month', 'months']:
        months_ago = int(date.split(' ')[0])
        return datetime.now() - timedelta(days=30 * months_ago)

data_job['postdate'] = data_job['postdate'].apply(lambda x: convert_date(x))
data_job.head()

Cleaning jobtitle
Cleaning jobdescription

In [139]:
data_job.to_csv('data\data_job_clean.csv', header=True, index=False)

In [48]:
# Vectorization TF-IDF
vectorizer = TfidfVectorizer()
matrix_title = vectorizer.fit_transform(data_job['jobtitle'])
matrix_description = vectorizer.fit_transform(data_job['jobdescription'])

# Similarity calculus
similarities_title = cosine_similarity(matrix_title)
similarities_description = cosine_similarity(matrix_description)

In [146]:
# Save the models in a file 
with open('models\similarties_title.pkl', 'wb') as file:
    pickle.dump(similarities_title, file)

with open('models\similarities_description.pkl', 'wb') as file:
    pickle.dump(similarities_description, file)

In [60]:
# Example usage
title_example = data_job.loc[0]['jobtitle']
print(title_example)
print()

temp = sorted(list(enumerate(similarities_title[0])), key=lambda x: x[1], reverse=True)[1:20]
for idx, score in temp:
    print(data_job.loc[idx]['jobtitle'])

automation test engineer

automation test engineer
test automation engineer
automation test engineer
test automation engineer
test automation engineer
automation test engineer
senior automation test engineer
software test automation engineer
software test automation engineer
sr test automation engineer
sr test automation engineer
sr test automation engineer
test lead automation engineer
lead test automation engineer
lead test automation engineer
automation test manager
test automation architect
automation test architect
automation test architect

In [103]:
def detect_keywords(main_string, keywords):
    main_list = main_string.split(' ')
    keywords_list = keywords.split(' ')
    return all(keyword in main_list for keyword in keywords_list)

def search(input_text, **kwargs):
    """
    Search for a job in the dataset based on the input text and optional filters.

    Parameters:
    - input_text (str): Text entered by the user.
    - **kwargs (dict): Filters for company, employmenttype_jobstatus, and joblocation.

    Returns:
    pd.Series: The line in the dataset that matches the criteria, or None if no match is found.
    """
    # Initialize a mask to filter the dataset
    mask = (data_job['jobtitle'].apply(lambda x: detect_keywords(x, input_text)) | data_job['jobtitle'].str.contains(input_text, case=False, na=False))

    # Apply additional filters if provided
    for key, value in kwargs.items():
        mask &= (data_job[key] == value)

    # Get the matching row from the dataset
    result = data_job[mask]

    # Return the result (a DataFrame if there are matches, None otherwise)
    return result if not result.empty else None

example = search('automation engineer', employmenttype_jobstatus='Full Time', company='Computer Consultants Interchange')
example

,company,employmenttype_jobstatus,jobdescription,joblocation_address,jobtitle,postdate,shift,skills
2483,Computer Consultants Interchange,Full Time,top consumer service organization seeking auto...,"Bridgeport, CT",automation test engineer,1 week ago,Telecommuting not available|Travel not required,"Selenium, Java, SQL"

In [142]:
def calculate_recency_bonus(date_published):
    current_date = datetime.now()
    delta = current_date - date_published
    days_ago = delta.days
    return max(0, 0.5 - days_ago * 0.02)  # Bonus decreases linearly over time

def recommendation_search(search_result, **kwargs):
    """
    Search for job recommendations based on a given search result and optional filters.

    Parameters:
    - search_result (pd.Series): The line in the dataset that matches the criteria, or None if no match is found.
    - **kwargs (dict): Optional filters for company, employmenttype_jobstatus, and joblocation.

    Returns:
    - pd.Series: Job titles that match the search criteria and filters, sorted by relevance. Top 11 as the first one is tu current search

    Notes:
    - The function calculates a relevance score based on the similarity of the job title and description.
    - Top 10 jobs with the highest relevance scores are returned.
    - Additional filters can be applied using **kwargs to refine the search.
    - A recency bonus is applied to prioritize more recent job postings.

    Formula used : score = 0.3 * title_similarity + 0.7 * description_similitary + sum(1 for each filter macthed) + max(0, 0.5 - days_ago * 0.02)

    """
    # Find index of the search
    indx = search_result.index[0]

    # Get similarities with this search
    score_title = list(enumerate(similarities_title[indx]))
    score_description = list(enumerate(similarities_description[indx]))

    # Calculate relevance scores for each job
    scores = {score_title[i][0]: score_title[i][1] * 0.3 + score_description[i][1] * 0.7 for i in range(len(score_title))}
    scores = dict(sorted(scores.items(), key=lambda x: x[1], reverse=True)[:11])

    # Apply additional filters if provided
    if kwargs:
        for idx, score in scores.items():
            temp = data_job.loc[idx]
            for col, value in kwargs.items():
                if value.lower() in temp[col].lower():
                    scores[idx] += 1
    
    # Apply recency bonus
    for idx in scores.keys():
        recency_bonus = calculate_recency_bonus(data_job.loc[idx]['postdate'])
        scores[idx] += recency_bonus

    # Get top 10 jobs based on the combined relevance score and filters
    scores = dict(sorted(scores.items(), key=lambda x: x[1], reverse=True)[:10])

    # Create a DataFrame with job titles, filter values, and scores
    res = data_job.loc[scores.keys()][['jobtitle'] + list(kwargs.keys())]
    res['score'] = [scores[idx] for idx in scores]

    return res

recommendation_search(example, employmenttype_jobstatus='Full Time', company='Computer Consultants Interchange')

,jobtitle,employmenttype_jobstatus,company,score
2483,automation test engineer,Full Time,Computer Consultants Interchange,3.360000
8849,automation test lead,"Full Time, Full Time",Capital Markets Placement,2.035711
299,qa test automation engineer,Full Time,Verys,1.967988
15650,cloud test automation engineer,Full Time,Centage Corporation,1.697745
8484,test automation engineer,"Full Time, Full Time","Agreatis, Inc.",1.623455
17022,automation test lead,Full Time,Wolters Kluwer TeamMate,1.483912
12905,test lead automation engineer,Full Time,Dynanet Corporation,1.459102
11351,test engineer,Market related,Randstad Technologies,0.958189
21497,automation test engineer,"Contract W2, 4-6 months onsite",Advanced Software Talent,0.873236
20366,software automation engineer,"Contract Independent, Contract W2","Software Technology, Inc.",0.510008